### ISSUE TITLE
How does this Package work?

### ISSUE THREAD

**Issue by zionnite** [azkadev/telegram_client#10]
Hello,
Thanks for this awesome package but am in doubt how this package work.

This is what I want to accomplish.

I want to use your package to create an App for church, so that user can message them self and as well download videos and music. But do user need to have telegram account before they can use this App am building with your package?

I need your swift reply

**Comment by azkadev** [comment]
You can use with your bot token, but I don't recommend that way,
why?:
1. It's illegal
2. It's a sneaky way (poor)

If you have the funds it's better to build a server for your application so you don't burden Telegram,
