### ISSUE TITLE
How to make it work on iOS?

### ISSUE THREAD

**Issue by Skrip0v** [azkadev/telegram_client#11]

**Comment by azkadev** [comment]
I haven't tried it on iOS because I don't have a device but you can try it yourself,
1. Build tdlib for ios Devices


if there are difficulties you can ask on stackoverflow / comment on this github,

**Comment by Skrip0v** [comment]
Yes, I already built files for ios and other apple operating systems using this tutorial - https://github.com/tdlib/td/tree/master/example/ios
These files look like this:
<img width="763" alt="Снимок экрана 2022-07-30 в 10 08 31" src="https://user-images.githubusercontent.com/93714842/181879208-1782fa5c-bef8-42a2-8843-124b1a52ea59.png">

**But I don't know where to put them and make it work. Do you have any ideas?**

**Comment by azkadev** [comment]
Sorry I don't know how to add dynamic library to my ios project, Sorry it took me a long time to respond, sorry I can't help much because I've asked in the flutter group but no one member replied

**Comment by Skrip0v** [comment]
OK, thanks for trying to help :)
