### ISSUE TITLE
The request sendMessage returns an error USERNAME_INVALID

### ISSUE THREAD

**Issue by Wolfaks** [azkadev/telegram_client#13]
Hello.
I successfully logged in with my account, but when I try to send a message, an error is returned. For some reason, the chat ID is inserted into the username field, which I set in the parameters:
`    var res = await tgObj.request("sendMessage", parameters: {
      "chat_id": dialogID,
      "text": text
    });
    print(res);
// dialogID ==  290672990
// text == "12345"
`
The request sendMessage returns an error USERNAME_INVALID:
`Unhandled Exception: {@type: error, code: 400, message: USERNAME_INVALID, invoke_request: {@type: searchPublicChat, client_id: -5476376659015607984, username: 290672990, @extra: e73lhg0x0eajnba}}`

I need your help. thanks a lot

**Comment by azkadev** [comment]
make sure the chat id format into int

**Comment by Wolfaks** [comment]
Thank you very much. This solved my issue.
