### ISSUE TITLE
How add text message with photo using the method sendPhoto

### ISSUE THREAD

**Issue by Wolfaks** [azkadev/telegram_client#14]
Hello. I use the method sendPhoto and i need to send text message with photo.
How i can do it? 

I tried to add 'text' key but it doesn't work. I need to send one photo with text. Or some photos. Thank you.

`var res = await tgObj.request("sendPhoto", parameters: {
      "chat_id": dialogID,
      "photo": photo
    });`

**Comment by azkadev** [comment]
add parameter key caption

lihat document official https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_function.html

/ document bot api 
https://core.telegram.org/bots/api
