### ISSUE TITLE
Problem with getChats call

### ISSUE THREAD

**Issue by Wolfaks** [azkadev/telegram_client#15]
Hello.
I have appeared problem with getChats call.
This call stopped returning a result:

`Map<String, dynamic> parameters = {
      "limit": "1000000000"
    };`

`await tgObj.debugRequest("loadChats", parameters: parameters, callback: (res) async {
print(res);
});`

Such a call works, but does not return a list of chats with information about them (photo, title, name, etc.). Only a list with a list of chat ids is returned.
`var newRes = await tgObj.invoke("getChats", parameters: parameters);
print(newRes);`

Even though I didn't update anything. Everything stopped working on its own. Please help me solve the problem with displaying the list of user chats. I need not only a list of ids, but also information about the chats. Thanks a lot.

**Comment by azkadev** [comment]
You use the raw method if you want to display details along with the username title and so on, you have to change the method to request

```dart
var newRes = await tgObj.request("getChats", parameters: parameters);
print(newRes);
```

**Comment by Wolfaks** [comment]
`var res = await tgObj.request("loadChats", parameters: parameters);`
result: {@type: ok}

but
`Map<String, dynamic> parameters = {
       "limit": "1000000000"
};
var newRes = await tgObj.request("getChats", parameters: parameters);
print(newRes);`
Returns no result. Execution stops or long wait. Previously worked. I didn't update anything. Limit 1 is the same.

**Comment by azkadev** [comment]
yes because you use very large numbers

**Comment by Wolfaks** [comment]
`Map<String, dynamic> parameters = { "limit": "1" };`
Doesn't solve the problem..

**Comment by Wolfaks** [comment]
I know that telegram added sub-chats in the main chat list. Could it break the work? Everything worked before.

**Comment by Wolfaks** [comment]
@azkadev Thank you for the corrections. The new version fixed the issue.
