### ISSUE TITLE
client execute

### ISSUE THREAD

**Issue by Ilyosxon2721** [azkadev/telegram_client#17]
hi please tell me how to fix this error.
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol '_td_json_client_execute': undefined symbol: _td_json_client_execute

**Comment by azkadev** [comment]
If you use tdlib on android you should use the tdlib library that I have compiled, please use it in my github release
