### ISSUE TITLE
Can we Stream Telegram Video Files in Flutter Mobile by this lib ? 

### ISSUE THREAD

**Issue by rohitsangwan01** [azkadev/telegram_client#4]
As described in Title , can we stream Videos , or upload videos to telegram from our Android or IOS app
btw , great package ✌️

**Comment by azkadev** [comment]
yes, you can find the method here to download the file first [getFile](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_file.html)

then call method [downloadFile](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1download_file.html)

**Comment by rohitsangwan01** [comment]
@azkadev thanks , but looks like this will download the file , can we stream directly without downloading ?

**Comment by azkadev** [comment]
> @azkadev thanks , but looks like this will download the file , can we stream directly without downloading ?

https://github.com/tdlib/td/issues/1498#issuecomment-819869719

**Comment by rohitsangwan01** [comment]
@azkadev got it , so basically we have to download with offset to download mini parts and play them , which behaves like kind of streaming video

**Comment by azkadev** [comment]
Yeah like that

**Comment by rohitsangwan01** [comment]
Thanks ✌️
