### ISSUE TITLE
how to include native library tdlib for android?

### ISSUE THREAD

**Issue by gwcangtip** [azkadev/telegram_client#5]
I'm new to building android apps, how do I add native libraries to Android?

**Comment by azkadev** [comment]
add this in folder android/app/build.gradle [Azkagram-build.gradle](https://github.com/azkadev/azkagram/blob/54882e8bdfc24745bb4fb752acac8843abed911b/android/app/build.gradle#L42)

```bash
sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main {
            jniLibs.srcDirs = ['src/jniLibs']
        }
}
```
then you compile [tdlib](https://github.com/tdlib) yourself

quickstart:
- [Tddroid](https://github.com/b68h4/tddroid)

or you can download tdlib on [Release Pages](https://github.com/azkadev/telegram_client/releases)
