### ISSUE TITLE
example does not start

### ISSUE THREAD

**Issue by denisnadey** [azkadev/telegram_client#9]
Tdlib tg = Tdlib("libtdjson.so", {
    'database_directory': "./client/", 
    'files_directory': "./client/",
  });

libtdjson.so is not generated

**Comment by azkadev** [comment]
change libtdjso.so to library path

example
```dart
Tdlib tg = Tdlib("/home/azkadev/td/build/libtdjson.so", {
'database_directory': "./client/",
'files_directory': "./client/",
});
```

**Comment by denisnadey** [comment]
how build library ?

**Comment by azkadev** [comment]
https://tdlib.github.io/td/build.html?language=dart
